#ifndef ERRORS_H__
#define ERRORS_H__

#define OK 0
#define ERROR_LEN_MODE 400
#define ERROR_VALUE_MODE 401
#define ERROR_ADD_MEMORY 402
#define ERROR_CNT_COEFFICIENTS 403
#define ERROR_INPUT_VAL 404
#define ERROR_INPUT_COEFFICIENT 405
#define ERROR_INPUT_MORE_COEFFICIENT 406
#define ERROR_TEST 407

#endif
