#ifndef CONSTS_H__

#define CONSTS_H__

#define MODE_POP_FRONT 101
#define MODE_POP_END 102
#define MODE_SORT 103
#define MODE_SORT_POP_FRONT_END 104
#define MODE_POP_DUPLICATES 105
#define MODE_POP_DUPLICATES_SORT 106

#endif
