#ifndef ERRORS_H__

#define ERRORS_H__

#define OK 0
#define ERROR 300
#define ERROR_OPEN_FILE_IN 300
#define ERROR_OPEN_FILE_OUT 301
#define ERROR_LEN_FILE 302
#define ERROR_ARGUMENTS 303
#define ERROR_READ_PRICE 304
#define ERROR_ADD_MEMORY 305
#define ERROR_CHOICE_MENU 306

#endif
