#ifndef ERRORS_H__

#define ERRORS_H__

#define OK 0
#define ERROR 300
#define ERROR_OPEN_FILE 300
#define ERROR_LEN_FILE 301
#define ERROR_ARGUMENTS 302
#define ERROR_READ_YEAR 304
#define ERROR_YEAR 305
#define ERROR_LEN_NAME 306
#define ERROR_LEN_GROUP 307
#define ERROR_ADD_MEMORY 308
#define ERROR_FIND 309

#endif
